### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by oleksandr-jr** [OnDecember/Animal-Life-Simulator#1]
The OOP structure of the project is done well.
I liked the idea of the Controllers it's a good way to implement the actions of the animals.
I can say that all the topics of the module were covered in this project, and you did a great job.
I'm happy to see that you followed some of my recommendations to improve the project and implemented them on your own way.
You did a great job with stream API and lambda expressions.

If I understand right the GlobalVariables class blocks the whole program and only one operation can be executed.
It could be a problem if you want to add more actions in the future.
You can clean the code a little bit and remove the unused imports.

I see that you have invested a lot of time and effort in this project, and I am very happy about it.
I wish you good luck in your future projects and I hope to see your projects in the next modules.

**Comment by Y-Maxym** [comment]
Thank you for your feedback. I will try to continue making projects
